export const searchValue = [
  'subject:subject:Architecture',
  'subject:Art',
  'subject:Biography & Autobiography',
  'subject:Business',
  'subject:Crafts & Hobbies',
  'subject:Drama',
  'subject:Fiction',
  'subject:Cooking',
  'subject:Health & Fitness',
  'subject:History',
  'subject:Humor',
  'subject:Poetry',
  'subject:Psychology',
  'subject:Science',
  'subject:Technology',
  'subject:Travel',
];
