export const topBooks = [
  'A Heart That Works',
  'Afterlives',
  'All the Lovers in the Night',
  'All This Could Be Different',
  'An Immense World',
  'Ancestor Trouble',
  'Animal Joy',
  'Anna: The Biography',
  'Babel',
  'Bitter Orange Tree',
  'The Book of Goose',
  'Breathless',
  'Butts: A Backstory',
  'Calling for a Blanket Dance',
  'The Candy House',
  'Carrie Soto Is Back',
  "Chef's Kiss",
  'Civil Rights Queen',
  'Constructing a Nervous System',
  'Cover Story',
  'The Crane Wife',
  'The Daughter of Doctor Moreau',
  'Dinosaurs',
  'Dirtbag, Massachusetts',
  'Ducks: Two Years in the Oil Sands',
  'Easy Beauty',
  'Eating to Extinction',
  'Either/Or',
  'The Emergency',
  'The Employees',
  'The Escape Artist',
  'Everything I Need I Get from You',
  'The Extraordinary Life of an Ordinary Man',
  'The Family Outing',
  'Fellowship Point',
  'Finding Me',
  'Fiona and Jane',
  'The Furrows',
  'Getting Lost',
  'Glory',
  'Goliath',
  'Half American',
  'The Hero of This Book',
  'His Name Is George Floyd',
  'Honey & Spice',
  'How Far the Light Reaches',
  'The Hurting Kind',
  'I Came All This Way to Meet You',
  "I'm Glad My Mom Died",
  'If an Egyptian Cannot Speak English',
  'If I Survive You',
  'In Love',
  'Index, A History of the',
  'The Invisible Kingdom',
  'Learning to Talk',
  'Lesser Known Monsters of the 21st Century',
  'Liberation Day',
  'Life Between the Tides',
  'The Light We Carry',
  'Lost & Found',
  'Lucy by the Sea',
  'The Man Who Could Move Clouds',
  'Manifesto',
  'Maps of Our Spectacular Bodies',
  'The Marriage Portrait',
  'The Method',
  'Mouth to Mouth',
  "The Naked Don't Fear the Water",
  'Night of the Living Rez',
  'Nightcrawling',
  'Now Is Not the Time to Panic',
  'Nuclear Family',
  'Olga Dies Dreaming',
  'Our Missing Hearts',
  'The Rabbit Hutch',
  'The Revolutionary: Samuel Adams',
  'Scattered All Over the Earth',
  'The School for Good Mothers',
  'Scoundrel',
  'Shrines of Gaiety',
  'Signal Fires',
  'Siren Queen',
  'South to America',
  'Stay True',
  'Still Life',
  'Strangers to Ourselves',
  'Ted Kennedy: A Life',
  'This Time Tomorrow',
  'Tides',
  'Time Is a Mother',
  'Tomorrow, and Tomorrow, and Tomorrow',
  'The Trayvon Generatio',
  'Trust',
  'Upgrade',
  'Love Marriage',
  'Vladimir',
  'When We Were Sisters',
  'Woman Without Shame',
  'The World Keeps Ending, and the World Goes On',
  'Young Mungo',
];
